[application]

# App name
name = "dioxus_demo"

# The Dioxus platform to default to
default_platform = "web"

[web.app]

# HTML title tag content
title = "solana_with_rust"

[web.watcher]

# When watcher is triggered, regenerate the `index.html`
reload_html = true

# Which files or dirs will be monitored
watch_path = ["src"]

# Include style or script assets
[web.resource]

# CSS style file
style = [
    "https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.css",
    "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css",
]

# Javascript code file
script = ["https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.js"]

[web.resource.dev]
